### ISSUE TITLE
Cant close the menu

### ISSUE THREAD

**Issue by chopo156** [ThymonA/menuv#16] opened 2020-12-24 19:38 UTC
Hi Tigo i just create a simple menu with a bunch of buttons just for testing, one of those buttons are the "close" one.
So i do 
```
 MechMenu1 = MenuV:CreateMenu("MECHANIC MENU","", 'size-150')
		 MenuV:OpenMenu(MechMenu1, function()
		 end)
```
then 
 `local buybutton = MechMenu1:AddButton({icon ="🧑‍🔧 	",label = "Close Menu" , value = 1,description = 'Close the Menu'  })`
and in the On Event
```
buybutton:On("select",function()
			-- MenuV:CloseMenu(MechMenu1)
			 MechMenu1:Close()
			 print("CALLED MENU CLOSE")

		 end)
```
but it never close itself, i dont know but maybe im doing something wrong, i get the "CALLED MENU CLOSE" in the console

**Comment by ThymonA** [comment] 2020-12-24 20:00
Which version are you using?

**Comment by chopo156** [comment] 2020-12-24 20:38
the last one

**Comment by chopo156** [comment] 2020-12-25 04:14
Another thing tigo, the Refresh doest work for me too, i add a number, then that number must increase the label of the button, but it never doest, i put the refresh() and doest nothing.

**Comment by ThymonA** [comment] 2020-12-25 08:55
It is strange that `MenuV:Refresh()` isn't working, because what that function does is reloading the complete menu.
Its seems more like your not using the latest version, because some of those bugs your encounter are already fixed.
If your sure your using the latest version, send me your menu resource (not menu, just the resource with `MenuV:CreateMenu` etc.

You can send it to one of the following:
**Discord** Tigo#9999
**Mail** contact@thymonarens.nl
**Here** as attachment (public visible)

Maybe the I can find the problem why MenuV isn't working for you.

**Comment by chopo156** [comment] 2020-12-26 05:23
Hi Tigo is chopo156 here, 
[example.zip](https://github.com/ThymonA/menuv/files/5742712/example.zip)
i use the default example

**Comment by ThymonA** [comment] 2021-01-11 10:36
Close this issue because I couldn't reproduce it. I will till investigate this in another issue/update #15

**Closed by ThymonA** 2021-01-11 10:36 UTC
Labels: Bug

**Comment by robertne13** [comment] 2022-02-16 04:08
same issue here 
![image](https://user-images.githubusercontent.com/39007106/154194278-59ccd1a7-c0bb-4b2f-aa2b-aa6b32f9c534.png)
i try 
menu:Close()
MenuV:CloseAll()
MenuV:CloseMenu(menu)
i create the menu like this 
local menu = MenuV:CreateMenu(false, 'Editar Vehiculo', 'topright', 220, 20, 60, 'size-125', 'none', 'menuv', 'test')

**Comment by Collaze** [comment] 2022-03-01 14:09
> 

Same

**Comment by Collaze** [comment] 2022-03-01 14:10
I'm getting the same as the guy above me ^^^^^
